### ISSUE TITLE
ตั้งชื่อให้เรียงตามลำดับที่จะรัน (lexical ordering)

### ISSUE THREAD

**Issue by kkalavantavanich** [team-chim/ddl#1]
ตอนรัน import_sql.sh มันจะรันตามลำดับตัวอักษร (lexical ordering) ช่วยเรียงทุกไฟล์ตามลำดับหน่อย

**Comment by kkalavantavanich** [comment]
For example: `30_table_report_deadlines.sql` and `30_trigger_insert_semester.sql`.

**Comment by munggumy** [comment]
duplicate number files are deleted
